# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f12c5772983b0191158c7e8540b7baa0021f23b323346aa1d8d6b09399e91ce13076495ffdce9e9f246da7b36cea5de0cce14dcdb55fe88aeba4c1866f48ec

test:
  secret_key_base: 8618a520d9082592eb3664c88af749dff0a8f4012b428a3b1b2438a7c9253fcc031c434015d2229124029b767df39b261a934aed1784acf4f5e64fd830dbf935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
